local LuaToken = require "LuaToken"

describe("LuaToken", function()
    describe("new()", function()
        it("sets fields", function ()
            local token = LuaToken.new("<number>", "3.14", 3.14, 1)
            assert.are.same("<number>", token.type)
            assert.are.same("3.14", token.lexeme)
            assert.are.same(3.14, token.literal)
            assert.are.same(1, token.line)
        end)
    end)
    describe("token:tostring()", function()
        it("returns a string with its type, lexeme and literal", function ()
            local token = LuaToken.new("<number>", "3.14", 3.14, 1)
            assert.are.same("<number> 3.14 3.14 1", token:tostring())
        end)
    end)
    describe("tostring(token)", function()
        it("returns a string with its type, lexeme and literal", function ()
            local token = LuaToken.new("<number>", "3.14", 3.14, 1)
            assert.are.same("<number> 3.14 3.14 1", tostring(token))
        end)
    end)
    describe("token:trimCommentEndline()", function()
        it ("should remove any \\r character at the end of the lexeme", function()
            local token = LuaToken.new("COMMENT", "--comment\r", nil, 1)
            token:trimCommentEndline()
            assert.are.same("COMMENT --comment nil 1", tostring(token))
        end)
        it ("should remove any \\n character at the end of the lexeme", function()
            local token = LuaToken.new("COMMENT", "--comment\n", nil, 1)
            token:trimCommentEndline()
            assert.are.same("COMMENT --comment nil 1", tostring(token))
        end)
    end)
end)