local LuaToken = require "LuaToken"

describe("LuaToken", function()
    describe("new()", function()
        it("sets fields", function ()
            local token = LuaToken.new(LuaToken.Number, "3.14", 3.14, 1)
            assert.are_same(LuaToken.Number, token.type)
            assert.are_same("3.14", token.lexeme)
            assert.are_same(3.14, token.literal)
            assert.are_same(1, token.line)
        end)
    end)
    describe("tostring()", function()
        it("returns a string with its type, lexeme and literal", function ()
            local token = LuaToken.new(LuaToken.Number, "3.14", 3.14, 1)
            assert.are_same("Number 3.14 3.14 1", token:tostring())
        end)
    end)
    describe("tostring(token)", function()
        it("returns a string with its type, lexeme and literal", function ()
            local token = LuaToken.new(LuaToken.Number, "3.14", 3.14, 1)
            assert.are_same("Number 3.14 3.14 1", tostring(token))
        end)
    end)
end)